name: SonarQube CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Tests (optional)
        working-directory: ./backend
        run: npm test || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality Gate Check
        id: qualitygate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Fetch Sonar Report
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "${{ secrets.SONAR_HOST_URL }}/api/issues/search?projectKeys=hospital-management-system" \
          > report.json

      - name: Send Email - Success
        if: steps.qualitygate.outputs.quality_gate_status == 'PASSED'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Pipeline Successful - No Vulnerabilities"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: report.json
          body: |
            ✅ No vulnerabilities found.

            Quality Gate: PASSED

            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}

      - name: Send Email - Failure
        if: steps.qualitygate.outputs.quality_gate_status != 'PASSED'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Pipeline Failed - Vulnerabilities Found"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: report.json
          body: |
            ❌ Vulnerabilities detected.

            Quality Gate: FAILED

            Please check SonarQube Dashboard:
            ${{ secrets.SONAR_HOST_URL }}

            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}

